## Numpy Arrays

In [3]:
import numpy as np

### Vectors
First lets look at one-dimensional arrays. You will find that in a lot of ways these work similarly to lists that we looked at in the previous notebook.

In [20]:
arr = np.array([0, 1, 2, 3, 4])
type(arr)

numpy.ndarray

We can for-loop over these arrays in the same way that we looped over lists.

In [18]:
print('array shape =', arr.shape)

for i in arr:
    print(i*i)


array shape = (5,)
0
1
4
9
16


We can examine and alter elements of arrays easily:

In [24]:
print(arr[3])
arr[3] = 100
print(arr[3])
print(arr)

100
100
[  0   1   2 100   4]


### Matrices
So far we've looked at one-dimensional arrays, now lets look at two-dimensional ones. In the lectures, we refer to these at matrices.

In [40]:
M = np.array([[1,0],[0,1],[1,0]])
print(M)
print('The shape of M is', M.shape)
print('The height of M is', M.shape[0]) # Remember indexing starts at 0
print('The width of M is', M.shape[1])

[[1 0]
 [0 1]
 [1 0]]
The shape of M is (3, 2)
The height of M is 3
The width of M is 2


We can create certain matrices quickly with some standard numpy functions.

In [72]:
z2 = np.zeros((2,2))
print(z2)

[[0. 0.]
 [0. 0.]]


In [74]:
z4 = np.zeros((4,4))
print(z4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [78]:
o3= np.ones((3,3))
print(o3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [83]:
rand2 = np.random.random((2,2))
print(rand2)

[[0.38411492 0.5201803 ]
 [0.56853952 0.41001648]]


#### Slicing Matrices
Matrices can be inspected and examined in the same way as one-dimensional arrays. We will go into a little more depth here.

In [ ]:
mat = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(mat)

In [100]:
print('The centre of the matrix is', mat[1,1])
print('The top row of the matrix is', mat[0]) #Note that this gets the top row, not the left-most column
print('The left-most column of the matrix is', mat[:,0])

The centre of the matrix is 4
The top row of the matrix is [0 1 2]
The left-most column of the matrix is [0 3 6]


We can use `:` to inspect chunks of the matrix together. Infact, when we do `mat[0]` this is shorthand for `mat[0,:]`.

`:` can be used in several different ways. 

In the following example, where `:` is on its own, we get all values: `mat[0,0], mat[1,0], mat[2,0]`

In [102]:
mat[:,0]

array([0, 3, 6])

This time, we will use another colon to the right of the comma. The first colon is the same as before but the second one now tells python that we want all values where the second index is less than 2. So we get `[mat[0,0], mat[0,1]]`, `[mat[1,0], mat[1,1]]`, `[[mat[2,0], mat[2,1]]`

In [104]:
mat[:, :2]

array([[0, 1],
       [3, 4],
       [6, 7]])

Our matrix has column indices `0, 1, 2` and row indices `0, 1, 2`.  in `mat[:2,:]` 

In [106]:
print('The rightmost two columns of the matrix are \n', mat[:, 1:]) 

print('The top left square of the matrix is \n', mat[:2,:2])

The rightmost two columns of the matrix are 
 [[1 2]
 [4 5]
 [7 8]]
The top left square of the matrix is 
 [[0 1]
 [3 4]]


### Operations on arrays