## Numpy Arrays

In [3]:
import numpy as np

### Numpy Functions
Before we get into details, let's have a look at how we can call numpy functions. We will create two arrays `a1` and `a2`, we'll go into more depth about these soon.

In [146]:
a1 = np.array([0,1])
a2 = np.array([1,2])

print(type(a1))
print(type(a2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


To call a function from the numpy library, we use `np.function_name`

In [147]:
np.add(a1, a2)

array([1, 3])

#### Numpy methods
Sometimes, we can call a method which is inbuilt into the class of an object. As we see above, `a1` and `a2` are of numpy ndarrays. If we look at the [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html), there are multiple 'methods' which can be called. We can call these methods in a more efficient way if we wish. In the next few cells, we'll take a look at two methods in the list, `dot` and `sum`.

In [155]:
# The normal way
np.dot(a1,a2)

2

In [157]:
# Alternative
a1.dot(a2)

2

In [158]:
# Normal
np.sum(a2)

3

In [161]:
a2.sum()

3

### Vectors
First let's look at one-dimensional arrays. You will find that in a lot of ways these work similarly to lists that we looked at in the previous notebook.

In [20]:
arr = np.array([0, 1, 2, 3, 4])
type(arr)

numpy.ndarray

We can for-loop over these arrays in the same way that we looped over lists.

In [18]:
print('array shape =', arr.shape)

for i in arr:
    print(i*i)


array shape = (5,)
0
1
4
9
16


We can examine and alter elements of arrays easily:

In [24]:
print(arr[3])
arr[3] = 100
print(arr[3])
print(arr)

100
100
[  0   1   2 100   4]


### Matrices
So far we've looked at one-dimensional arrays, now let's look at two-dimensional ones. In the lectures, we refer to these at matrices.

In [40]:
M = np.array([[1,0],[0,1],[1,0]])
print(M)
print('The shape of M is', M.shape)
print('The height of M is', M.shape[0]) # Remember indexing starts at 0
print('The width of M is', M.shape[1])

[[1 0]
 [0 1]
 [1 0]]
The shape of M is (3, 2)
The height of M is 3
The width of M is 2


We can create certain matrices quickly with some standard numpy functions.

In [72]:
z2 = np.zeros((2,2))
print(z2)

[[0. 0.]
 [0. 0.]]


In [74]:
z4 = np.zeros((4,4))
print(z4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [78]:
o3= np.ones((3,3))
print(o3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [83]:
rand2 = np.random.random((2,2))
print(rand2)

[[0.38411492 0.5201803 ]
 [0.56853952 0.41001648]]


#### Slicing Matrices
Matrices can be inspected and examined in the same way as one-dimensional arrays. We will go into a little more depth here.

In [ ]:
mat = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(mat)

In [100]:
print('The centre of the matrix is', mat[1,1])
print('The top row of the matrix is', mat[0]) #Note that this gets the top row, not the left-most column
print('The left-most column of the matrix is', mat[:,0])

The centre of the matrix is 4
The top row of the matrix is [0 1 2]
The left-most column of the matrix is [0 3 6]


We can use `:` to inspect chunks of the matrix together. Infact, when we do `mat[0]` this is shorthand for `mat[0,:]`.

`:` can be used in several different ways. 

In the following example, where `:` is on its own, we get all values: `mat[0,0], mat[1,0], mat[2,0]`

In [102]:
mat[:,0]

array([0, 3, 6])

This time, we will use another colon to the right of the comma. The first colon is the same as before but the second one now tells python that we want all values where the second index is less than 2. So we get `[mat[0,0], mat[0,1]]`, `[mat[1,0], mat[1,1]]`, `[[mat[2,0], mat[2,1]]`

In [104]:
mat[:, :2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [106]:
print('The rightmost two columns of the matrix are \n', mat[:, 1:]) #The \n here starts a new line, just to make the output look a bit better.

print('The top left square of the matrix is \n', mat[:2,:2])

The rightmost two columns of the matrix are 
 [[1 2]
 [4 5]
 [7 8]]
The top left square of the matrix is 
 [[0 1]
 [3 4]]


### Operations on arrays

#### Matrix Duplication
Now we will look at some of the operations that numpy allows us to perform on arrays. First, let's look at how we might duplicate an array.

First, let's try:

In [129]:
x = np.array([[1,2],[3,4]])
y = x

print('x = \n', x)
print('y = \n', y)

x = 
 [[1 2]
 [3 4]]
y = 
 [[1 2]
 [3 4]]


In [130]:
y[0,0]=5
print(y)

[[5 2]
 [3 4]]


In [131]:
print(x)

[[5 2]
 [3 4]]


We only wanted to change `y`, but `x` has changed as well. This is because `y = x` only allows `y` to view the data, rather than creating a copy of it. That means that when `y` is altered, so is `x`.

Let's try again

In [132]:
x = np.array([[1,2],[3,4]])
y = x.copy()

print('x = \n', x)
print('y = \n', y)

x = 
 [[1 2]
 [3 4]]
y = 
 [[1 2]
 [3 4]]


In [133]:
y[0,0]=5
print(y)

[[5 2]
 [3 4]]


In [134]:
print(x)

[[1 2]
 [3 4]]


#### Mathematical Operators
Let's continue with the `x` and `y` we've just defined.

In [135]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 2]
 [3 4]]


**Matrix addition**

In [138]:
print(x+y)
print(np.add(x,y)) #Alternatively, you can use this format

[[6 4]
 [6 8]]
[[6 4]
 [6 8]]


**Matrix subtraction**

In [166]:
x-y

array([[-4,  0],
       [ 0,  0]])

**Matrix element-wise multiplication**

Note that this is element-wise multiplication, not standard matrix multiplication

In [165]:
x*y

array([[ 5,  4],
       [ 9, 16]])

**Matrix multiplcation**

In [163]:
np.dot(x,y)

array([[11, 10],
       [27, 22]])

Note that we have an alternative way of writing this. Because x and y are ndarrays, and `dot` is a method, we can use:

In [164]:
x.dot(y)

array([[11, 10],
       [27, 22]])

**Matrix summation**

In [168]:
np.sum(x)

10

In [169]:
x.sum() #Identical to the previous cell

10

In [174]:
print(np.sum(x, axis = 0))

[4 6]


In [175]:
print(x.sum(axis = 0)) #Shorthand way of writing it

[4 6]


In [176]:
print(np.sum(x, axis = 1))

[3 7]


In [177]:
print(x.sum(1)) # Even more shorthand. The 1 still refers to the axis, but we don't explicitly say it.

[3 7]


**Concatenation**